### ISSUE TITLE
Refactor overlay functionality

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#1154]
We need to move away from using Context and towards to proper state management via zustand

While we are at it, the refactored version of the overlay should allow to update the state of single values (e.g. update only `title`, `content`, `action1`, etc...)

It should also solve the issue with updating input fields inside the overlay `content` as currently, this is solved via a hack

**Comment by MManke188** [comment]
Fixed in https://github.com/Peach2Peach/peach-app/pull/1831
