### ISSUE TITLE
Fix `account` state management

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#1178]
At the moment we use a simple `account` variable throughout the app. Many components and hooks use it as a dependency.
As a result, if the `account` changes, the components and hooks will not be informed and do not rerender.

To fix this we need to move the `account` into a proper state management system such as `zustand`

- [x] contracts: https://github.com/Peach2Peach/peach-app/issues/1179
- [x] offers: https://github.com/Peach2Peach/peach-app/issues/1180
- [x] identity: https://github.com/Peach2Peach/peach-app/issues/1182
- [x] settings https://github.com/Peach2Peach/peach-app/issues/1184
- [x] paymentData https://github.com/Peach2Peach/peach-app/issues/1183
- [x] chats: https://github.com/Peach2Peach/peach-app/issues/1181

**Comment by MManke188** [comment]
da69fe08c5a881020ab6a0b9b29c809fdcd2427d
