### ISSUE TITLE
Fix `account` state management: offers

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#1180]
At the moment we use a simple `account` variable throughout the app. Many components and hooks use it as a dependency.
As a result, if the `account` changes, the components and hooks will not be informed and do not rerender.

To fix this we need to move the `account` into a proper state management system such as `zustand`

- [x] offers to zustand store
- [ ] cleanly separate client state from server state
- [x] add data migration script

**Comment by MManke188** [comment]
da69fe08c5a881020ab6a0b9b29c809fdcd2427d
