### ISSUE TITLE
Fix `account` state management: paymentData

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#1183]
At the moment we use a simple `account` variable throughout the app. Many components and hooks use it as a dependency.
As a result, if the `account` changes, the components and hooks will not be informed and do not rerender.

To fix this we need to move the `account` into a proper state management system such as `zustand`

- [x] `paymentData` to zustand store
- [x] add data migration script

**Comment by MManke188** [comment]
6715537d88d7667aaee043b290f442ab5831f382
