### ISSUE TITLE
Fix `account` state management: settings

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#1184]
At the moment we use a simple `account` variable throughout the app. Many components and hooks use it as a dependency.
As a result, if the `account` changes, the components and hooks will not be informed and do not rerender.

To fix this we need to move the `account` into a proper state management system such as `zustand`

- [x] settings to zustand store
- [x] add data migration script

**Comment by MManke188** [comment]
settingsStore was added baa70e89e0438f9239d9e21c776913e8ac6a6ba8
