### ISSUE TITLE
Peach app PGP key

### ISSUE THREAD

**Issue by TheGreatBeginner777** [Peach2Peach/peach-app#1978]
Hi,

please confirm if `... RSA key E970EDB410C8E84198F141584AD3CE3043D8CD1B` this key is valid Peach key. The only PGP key shown on website [https://peachbitcoin.com/apk/](url) is `48339A19645E2E53488E0E5479E1B270FACD1BD2`
If key is valid please add it to website as also valid key. Thank you for your time on this issue.

**Comment by lasermind** [comment]
This is indeed a problem and I opened an issue in the https://github.com/Peach2Peach/public-website/issues/150 repo. It's not a problem with the app, but with the webpage being not up to date.

**Comment by MManke188** [comment]
Thank you for reporting! I've added the key to my profile and also added it to the apk section of the website just now -> the previous pgp key link will still link to the hello@ email, since we use that for email communication but hopefully it's clear now
