### ISSUE TITLE
Address reuse bug with two sellers involved

### ISSUE THREAD

**Issue by CypherJack** [Peach2Peach/peach-app#2009]
I didn't saw it when it occurred but last year I had two different trades from two different sellers that arrived to the exact same address... yikes.
While managing my UTXO to consolidate them and moving them from my Peach wallet I came across a weird thing.
There is two sellers who I traded a couple time with each one of them that sent my coins to the exact same address. The trades were a separated by a week. I never manually use an address, letting Peach doing it automatically for myself. However due to the high fees environment I choosed very low manual fees because I wasn't in a hurry, only stacking some p2p sats. My guess is that the tx still was in the mempool and that Peach chose to use this address but I might be wrong.

I wont' share my PeachID publicly on here but would gladly give you the information you might need in private.

**Comment by MManke188** [comment]
Hey @CypherJack thank you for reporting and apologies for the delayed response!
The problem happens whenever a buyer creates multiple offers at the same time, because the last unused address is taken but it isn't considered 'used' until funds are on it. A fix will come shortly!

**Comment by MManke188** [comment]
Turns out I was not quite correct here. There was an issue with the persistent storage of the wallet, which is fixed with 471c4ab86c88391832334703f7a31fadd5c5dfd9 .  The corresponding next release will be out soon
