### ISSUE TITLE
Split saveOffer into separate functions

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#721]
The parameters disableSave and shield are not quite clear. To code easier to understand we should create separate functions such as for example

shieldedSaveOffer() and unshieldedSaveOffer()

---- 
also the function is supposed to save the offer, yet we have disableSave as a parameter. Proper refactoring is to create an accountStore and use it as accountStore.setOffer()

**Comment by MManke188** [comment]
da69fe0 latest with this this is fixed, both parameters are gone now
