### ISSUE TITLE
The HeaderSetup, as well as the error banners and help overlays still call navigation.navigate. Haven't noticed any bugs concerning this, but we should give it a second look (at some point)

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#781]
The HeaderSetup, as well as the error banners and help overlays still call navigation.navigate. Haven't noticed any bugs concerning this, but we should give it a second look (at some point)

_Originally posted by @MManke188 in https://github.com/Peach2Peach/peach-app/pull/779#discussion_r1082392297_

**Comment by MManke188** [comment]
Navigation is working fine, any actual in app bugs/improvements will be tackled on a case by case basis as we notice them
