### ISSUE TITLE
Refactoring for the future: I think it'd be nice if the hook would also return the current price in the displayCurrency of the user as well as moscow time

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#782]
Refactoring for the future: I think it'd be nice if the hook would also return the current price in the displayCurrency of the user as well as moscow time

_Originally posted by @MManke188 in https://github.com/Peach2Peach/peach-app/pull/780#discussion_r1082407325_

**Comment by MManke188** [comment]
ad17cf8a522dec2fc11aafaccf42f15a1a8882e6
