### ISSUE TITLE
Prefer `undefined` over `null` when returning nothing from a function

### ISSUE THREAD

**Issue by Czino** [Peach2Peach/peach-app#855]
In general, it's a good practice to return `undefined` when a value was not found, and null when the value was intentionally set to `null`. This helps other developers who are using your code to understand the intent behind your use of these values.

Therefore we should have a look over our functions that return `null` and check if it's not better to change it to `undefined`

**Comment by MManke188** [comment]
7520e7557e4b34a77e58d41e7c567fe2814f7b81
